version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: DockerfileAuth
    ports:
      - "8001:8000"
    volumes:
      - ./users.txt:/app/users.txt
    networks:
      - kuber_tut
  blog:
    build:
      context: .
      dockerfile: DockerfileBlog
    ports:
      - "8002:8000"
    environment:
      - "auth_app_url=http://auth:8000"
    networks:
      - kuber_tut
  calculator:
    build:
      context: .
      dockerfile: DockerfileCalculator
    ports:
      - "8003:8000"
    networks:
      - kuber_tut

networks:
  kuber_tut: